
project_id = "ftvvhclqjwtthquokzii"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[edge_functions]
[edge_functions.list-business-owners]
verify_jwt = true
