
project_id = "ftvvhclqjwtthquokzii"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000",
  "http://localhost:3000/auth",
  "http://localhost:3000/admin",
  "http://localhost:3000/owner"
]

[analytics]
enabled = false

[functions.manage-business-owners]
verify_jwt = true

[functions.manage-laundries]
verify_jwt = true

[functions.manage-machines]
verify_jwt = true
